-- Phase 0 foundation. Apply with: supabase db push
create type public.garment_category as enum ('top','bottom','dress','outerwear','shoe','accessory','jewelry','bag');
create type public.occasion_type as enum ('casual','formal','sport','party','work','sleep','ethnic');
create type public.season_type as enum ('summer','winter','spring','autumn','all');
create type public.mood_type as enum ('professional','casual','bold','cozy','party','minimal');
create type public.relationship_type as enum ('self','child','partner','other');
create type public.laundry_status as enum ('clean','dirty','washing','ironing');
create type public.alert_type as enum ('unused','growth','laundry','lend_return','hand_me_down','expiry','sale','ootd');
create type public.handover_target as enum ('sibling','cousin','donation','resale');
create type public.subscription_tier as enum ('free','premium','premium_plus');

create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text, avatar_url text, location_city text, lat float, lng float, subscription_tier public.subscription_tier default 'free', wear_threshold_days int default 180, growth_alert_months int default 3, notif_prefs jsonb default '{"unused":true,"growth":true,"laundry":true,"lend":true,"ootd":true,"sale":true}', fcm_token text, created_at timestamptz default now());
create table public.family_members (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, name text not null, relationship public.relationship_type default 'self', birth_date date, height_cm float, weight_kg float, current_size text, avatar_url text, created_at timestamptz default now());
create table public.garments (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, member_id uuid references public.family_members(id) on delete set null, name text not null, category public.garment_category not null, subcategory text, color_hex text, color_name text, secondary_colors text[], size text, brand text, price numeric(10,2), currency text default 'PKR', purchase_date date, occasions public.occasion_type[] default '{casual}', seasons public.season_type[] default '{all}', mood_tags public.mood_type[] default '{}', fabric text, wash_instructions text, barcode text, photo_urls text[] default '{}', image_hash text, wear_count int default 0, last_worn_date date, laundry_status public.laundry_status default 'clean', dirty_since timestamptz, condition_score int default 100 check (condition_score between 0 and 100), eco_score int check (eco_score between 0 and 100), resale_estimate numeric(10,2), is_archived boolean default false, archived_reason text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.outfits (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, name text, garment_ids uuid[] not null, mood public.mood_type, occasion public.occasion_type, season public.season_type, is_favorite boolean default false, times_worn int default 0, cover_photo_url text, created_at timestamptz default now());
create table public.wear_log (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, garment_id uuid not null references public.garments(id) on delete cascade, outfit_id uuid references public.outfits(id) on delete set null, worn_date date not null default current_date, weather_temp float, weather_cond text, created_at timestamptz default now());
create table public.alerts (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, type public.alert_type not null, garment_id uuid references public.garments(id) on delete cascade, member_id uuid references public.family_members(id) on delete cascade, title text not null, body text, is_read boolean default false, is_dismissed boolean default false, created_at timestamptz default now());
create table public.lend_borrow_log (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, garment_id uuid not null references public.garments(id) on delete cascade, direction text not null check (direction in ('lent','borrowed')), person_name text not null, date_out date default current_date, expected_return_date date, returned boolean default false, returned_date date);
create table public.hand_me_down_plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, garment_id uuid not null references public.garments(id) on delete cascade, from_member_id uuid references public.family_members(id), to_member_id uuid references public.family_members(id), target public.handover_target default 'sibling', target_season public.season_type, estimated_date date, done boolean default false);
create table public.wishlist_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, name text not null, category public.garment_category, brand text, color_name text, target_price numeric(10,2), current_price numeric(10,2), product_url text, photo_url text, sale_alert boolean default true, purchased boolean default false, created_at timestamptz default now());
create table public.packing_lists (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, trip_name text not null, destination text, start_date date, end_date date, outfit_ids uuid[] default '{}', extra_items jsonb default '[]', packed_garments jsonb default '{}', created_at timestamptz default now());
create table public.sharing_circles (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete cascade, invite_code text unique not null, invite_expires_at timestamptz, created_at timestamptz default now());
create table public.circle_members (circle_id uuid references public.sharing_circles(id) on delete cascade, member_user_id uuid references public.profiles(id) on delete cascade, can_vote boolean default true, joined_at timestamptz default now(), primary key (circle_id, member_user_id));
create table public.outfit_votes (id uuid primary key default gen_random_uuid(), outfit_id uuid not null references public.outfits(id) on delete cascade, voter_id uuid not null references public.profiles(id) on delete cascade, vote int not null check (vote in (-1, 1)), comment text, created_at timestamptz default now(), unique (outfit_id, voter_id));

create or replace function public.fn_after_wear() returns trigger language plpgsql security definer set search_path = public as $$ begin update public.garments set wear_count = wear_count + 1, last_worn_date = new.worn_date, laundry_status = 'dirty', dirty_since = now(), condition_score = greatest(condition_score - 1, 0) where id = new.garment_id; return new; end; $$;
create trigger trg_after_wear after insert on public.wear_log for each row execute function public.fn_after_wear();
create or replace function public.fn_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, full_name) values (new.id, new.raw_user_meta_data->>'full_name'); insert into public.family_members (user_id, name, relationship) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', 'Me'), 'self'); return new; end; $$;
create trigger trg_new_user after insert on auth.users for each row execute function public.fn_new_user();
create or replace function public.fn_touch() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger trg_garments_touch before update on public.garments for each row execute function public.fn_touch();

create view public.v_cost_per_wear as select g.id, g.user_id, g.name, g.price, g.wear_count, case when g.wear_count = 0 then g.price else round(g.price / g.wear_count, 2) end as cost_per_wear from public.garments g where g.is_archived = false and g.price is not null;
create view public.v_wardrobe_stats as select user_id, count(*) as total_items, sum(price) as total_value, round(avg(case when wear_count = 0 then price else price / wear_count end), 2) as avg_cpw, round(avg(eco_score)) as avg_eco_score from public.garments where is_archived = false group by user_id;
create index idx_garments_user on public.garments(user_id) where is_archived = false;
create index idx_garments_search on public.garments using gin (to_tsvector('simple', name || ' ' || coalesce(brand, '') || ' ' || coalesce(color_name, '')));
create index idx_garments_category on public.garments(user_id, category); create index idx_wear_log_garment on public.wear_log(garment_id, worn_date desc); create index idx_wear_log_user_date on public.wear_log(user_id, worn_date desc); create index idx_alerts_user on public.alerts(user_id, is_dismissed, created_at desc);

alter table public.profiles enable row level security; alter table public.family_members enable row level security; alter table public.garments enable row level security; alter table public.outfits enable row level security; alter table public.wear_log enable row level security; alter table public.alerts enable row level security; alter table public.lend_borrow_log enable row level security; alter table public.hand_me_down_plans enable row level security; alter table public.wishlist_items enable row level security; alter table public.packing_lists enable row level security; alter table public.sharing_circles enable row level security; alter table public.circle_members enable row level security; alter table public.outfit_votes enable row level security;
create policy "own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "own family members" on public.family_members for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own garments" on public.garments for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own outfits" on public.outfits for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own wear logs" on public.wear_log for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own alerts" on public.alerts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own lend borrow logs" on public.lend_borrow_log for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own hand me down plans" on public.hand_me_down_plans for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own wishlist items" on public.wishlist_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own packing lists" on public.packing_lists for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own sharing circles" on public.sharing_circles for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create policy "circle members visible to members" on public.circle_members for select using (member_user_id = auth.uid() or exists (select 1 from public.sharing_circles sc where sc.id = circle_id and sc.owner_id = auth.uid()));
create policy "circle owner manages members" on public.circle_members for all using (exists (select 1 from public.sharing_circles sc where sc.id = circle_id and sc.owner_id = auth.uid())) with check (exists (select 1 from public.sharing_circles sc where sc.id = circle_id and sc.owner_id = auth.uid()));
create policy "circle can view outfits" on public.outfits for select using (exists (select 1 from public.circle_members cm join public.sharing_circles sc on sc.id = cm.circle_id where cm.member_user_id = auth.uid() and sc.owner_id = outfits.user_id));
create policy "circle can vote" on public.outfit_votes for insert with check (auth.uid() = voter_id); create policy "voters view own votes" on public.outfit_votes for select using (auth.uid() = voter_id);

insert into storage.buckets (id, name, public) values ('garments', 'garments', false);
create policy "own garment photos" on storage.objects for all using (bucket_id = 'garments' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'garments' and (storage.foldername(name))[1] = auth.uid()::text);
